[package]
name = "meminfo-win"
version = "0.1.0"
edition = "2021"

[dependencies]
# Provides interaction with KERNEL.DLL from the Windows API.
kernel32-sys = "0.2"
# Defines some useful type aliases.
winapi = "0.2"
